name: Deploy Node Js
on: [push, workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
      uses: actions/checkout@v5
    - name: install Node
      uses: actions/setup-node@v6
      with: 
        node-version: 18
    - name: install dependency
      run: npm ci
    - name: lint code
      run: run npm lint
    - name: Test
      run: run npm test
    - name: build
      run: run npm build

